default_agent: eks_mcp_server_runtime
agents:
  eks_mcp_server_runtime:
    name: eks_mcp_server_runtime
    language: python
    node_version: null
    entrypoint: main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: .
    aws:
      execution_role: arn:aws:iam::175678592674:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-2eada2b69d
      execution_role_auto_create: false
      account: '175678592674'
      region: us-east-1
      ecr_repository: 175678592674.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-eks_mcp_server_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: eks_mcp_server_runtime-U2149HEFwB
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:175678592674:runtime/eks_mcp_server_runtime-U2149HEFwB
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-eks_mcp_server_runtime-builder
      execution_role: arn:aws:iam::175678592674:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2eada2b69d
      source_bucket: bedrock-agentcore-codebuild-sources-175678592674-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1npo1dcv21q1j8spmi00scio5
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_dBFkco4VY/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
