default_agent: a2a_troubleshooting_agent_runtime
agents:
  a2a_troubleshooting_agent_runtime:
    name: a2a_troubleshooting_agent_runtime
    entrypoint: /local/home/aksareen/2025/code.aws.dev/module-3/agentcore-connectivity-agent/main.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /local/home/aksareen/2025/code.aws.dev/module-3/agentcore-connectivity-agent
    aws:
      execution_role: arn:aws:iam::428903641150:role/performance-gateway-execution-role
      execution_role_auto_create: true
      account: '428903641150'
      region: us-east-1
      ecr_repository: 428903641150.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-a2a_troubleshooting_agent_runtime
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: a2a_troubleshooting_agent_runtime-gMo1GZB2ky
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:428903641150:runtime/a2a_troubleshooting_agent_runtime-gMo1GZB2ky
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-a2a_troubleshooting_agent_runtime-builder
      execution_role: arn:aws:iam::428903641150:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-07a0b34515
      source_bucket: bedrock-agentcore-codebuild-sources-428903641150-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: a2a_troubleshooting_agent_runtime_mem-VzUqPm5ARy
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:428903641150:memory/a2a_troubleshooting_agent_runtime_mem-VzUqPm5ARy
      memory_name: a2a_troubleshooting_agent_runtime_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_UkxveEuXk/.well-known/openid-configuration
        allowedClients:
        - 3n6g56ekr8au5nklnspf7c7pav
        - 7nc0ud1ccdfppv59uj6ic7m1ak
    request_header_configuration: null
    oauth_configuration: null
