AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Incident Analysis Agent System with Cognito authentication'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Cognito Configuration
        Parameters:
          - UserPoolName
          - MachineAppClientName
          - WebAppClientName

Parameters:

  UserPoolName:
    Type: String
    Default: 'IncidentAnalysisPool'
    Description: 'Name of the Cognito User Pool'

  MachineAppClientName:
    Type: String
    Default: 'IncidentAnalysisMachineClient'
    Description: 'Name of the Cognito User Pool Application Client'

  WebAppClientName:
    Type: String
    Default: 'IncidentAnalysisWebClient'
    Description: 'Name of the Cognito User Pool Web Application Client'

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      MfaConfiguration: 'OFF'
      UsernameConfiguration:
        CaseSensitive: false
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      Description: Administrator group
      UserPoolId: !Ref UserPool
      Precedence: 1

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: user
      Description: Regular user group
      UserPoolId: !Ref UserPool
      Precedence: 2

  WebUserPoolClient:
    DependsOn: ResourceServer
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref WebAppClientName
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
        - !Join
            - ''
            - - 'incident-resource-server-'
              - !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
              - '/invoke'
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:8502/
        - https://example.com/auth/callback
      LogoutURLs:
        - http://localhost:8502/
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      EnableTokenRevocation: true

  MachineUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: ResourceServer
    Properties:
      ClientName: !Ref MachineAppClientName
      UserPoolId: !Ref UserPool
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      RefreshTokenValidity: 1
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - !Join
          - ''
          - - 'incident-resource-server-'
            - !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
            - '/invoke'
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      EnableTokenRevocation: true

  ResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref UserPool
      Identifier: !Join
        - '-'
        - - 'incident-resource-server'
          - !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
      Name: !Join
        - '-'
        - - 'Incident Resource Server '
          - !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
      Scopes:
        - ScopeName: 'invoke'
          ScopeDescription: 'Invoke Incident Analysis agent runtime'

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join
        - ''
        - - 'incident-analysis-'
          - !Ref 'AWS::AccountId'

  # SSM Parameters
  CognitoMachineClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/machine_client_id
      Type: String
      Value: !Ref MachineUserPoolClient
      Description: Machine Cognito client ID
      Tags:
        Application: NetOps

  CognitoWebClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/web_client_id
      Type: String
      Value: !Ref WebUserPoolClient
      Description: Cognito client ID for web app
      Tags:
        Application: NetOps

  UserPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/userpool_id
      Type: String
      Value: !Ref UserPool
      Description: Cognito User Pool ID
      Tags:
        Application: NetOps

  CognitoProviderParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_provider
      Type: String
      Value: !Join
        - ''
        - - 'incident-analysis-'
          - !Ref 'AWS::AccountId'
      Description: Cognito provider name for BedrockAgentCore
      Tags:
        Application: NetOps

  CognitoAuthScopeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_auth_scope
      Type: String
      Value: !Join
        - ''
        - - 'incident-resource-server-'
          - !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
          - '/invoke'
      Description: OAuth2 scope for Cognito auth
      Tags:
        Application: NetOps

  CognitoDiscoveryURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_discovery_url
      Type: String
      Value: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}/.well-known/openid-configuration'
      Description: OAuth2 Discovery URL
      Tags:
        Application: NetOps

  CognitoTokenURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_token_url
      Type: String
      Value: !Join
        - ''
        - - !Sub 'https://incident-analysis-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/oauth2/token'
      Description: OAuth2 Token URL
      Tags:
        Application: NetOps

  CognitoAuthorizeURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_auth_url
      Type: String
      Value: !Join
        - ''
        - - !Sub 'https://incident-analysis-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize'
      Description: OAuth2 Authorization URL
      Tags:
        Application: NetOps

  CognitoDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/cognito_domain
      Type: String
      Value: !Join
        - ''
        - - !Sub 'https://incident-analysis-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'
      Description: Cognito hosted domain for OAuth2
      Tags:
        Application: NetOps

  # AgentCore Execution Role with ECR permissions
  AgentCoreExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'incident-gateway-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - bedrock-agentcore.amazonaws.com
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAgentCoreExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # ECR permissions for container runtime
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchCheckLayerAvailability
                Resource: '*'
              # BedrockAgentCore permissions (both control plane and runtime)
              - Effect: Allow
                Action:
                  - bedrock-agentcore-control:CreateOAuth2CredentialProvider
                  - bedrock-agentcore-control:DeleteOAuth2CredentialProvider
                  - bedrock-agentcore-control:GetOAuth2CredentialProvider
                  - bedrock-agentcore-control:ListOAuth2CredentialProviders
                  - bedrock-agentcore-control:UpdateOAuth2CredentialProvider
                  - bedrock-agentcore-control:CreateGateway
                  - bedrock-agentcore-control:DeleteGateway
                  - bedrock-agentcore-control:GetGateway
                  - bedrock-agentcore-control:ListGateways
                  - bedrock-agentcore-control:UpdateGateway
                  - bedrock-agentcore-control:CreateRuntime
                  - bedrock-agentcore-control:DeleteRuntime
                  - bedrock-agentcore-control:GetRuntime
                  - bedrock-agentcore-control:ListRuntimes
                  - bedrock-agentcore-control:UpdateRuntime
                  - bedrock-agentcore:InvokeRuntime
                  - bedrock-agentcore:GetResourceOauth2Token
                  - bedrock-agentcore:CreateMemory
                  - bedrock-agentcore:DeleteMemory
                  - bedrock-agentcore:GetMemory
                  - bedrock-agentcore:ListMemories
                  - bedrock-agentcore:UpdateMemory
                Resource: '*'
              # Lambda permissions for incident analysis MCP tools
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                  - lambda:ListFunctions
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:incident-*'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:netops-*'
              # CloudWatch read permissions for Container Insight Lambda
              - Effect: Allow
                Action:
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetDashboard
                  - cloudwatch:ListDashboards
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                  - logs:GetLogGroupFields
                  - logs:GetQueryResults
                  - logs:StartQuery
                  - logs:StopQuery
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: '*'
              # OpenSearch access for OpenSearch Lambda
              - Effect: Allow
                Action:
                  - es:ESHttpGet
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpDelete
                  - es:ESHttpHead
                  - es:DescribeElasticsearchDomains
                  - es:ListDomainNames
                Resource: '*'
              # SSM permissions for runtime configuration access
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:PutParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/incident/*'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/netops/*'
              # CloudWatch Logs permissions for debugging
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
              # IAM permissions for role operations (needed for some AgentCore operations)
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                  - iam:ListAttachedRolePolicies
                  - iam:ListRolePolicies
                  - iam:GetRolePolicy
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/incident-gateway-execution-role'
              # Service-linked role creation (commonly needed for AWS services)
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*'
              # X-Ray permissions for distributed tracing
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                Resource: '*'
              # Memory service permissions for BedrockAgentCore (least privilege)
              - Effect: Allow
                Action:
                  - bedrock-agentcore-memory:CreateMemory
                  - bedrock-agentcore-memory:DeleteMemory
                  - bedrock-agentcore-memory:GetMemory
                  - bedrock-agentcore-memory:ListMemories
                  - bedrock-agentcore-memory:UpdateMemory
                  - bedrock-agentcore-memory:PutMemoryData
                  - bedrock-agentcore-memory:GetMemoryData
                  - bedrock-agentcore-memory:DeleteMemoryData
                  - bedrock-agentcore:CreateEvent
                  - bedrock-agentcore:GetEvent
                  - bedrock-agentcore:ListEvents
                  - bedrock-agentcore:DeleteEvent
                Resource:
                  - !Sub 'arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:memory/IncidentAnalysisAgentMemory*'
                  - !Sub 'arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:memory/IncidentAnalysisAgentMemory*/*'
              # Secrets Manager permissions for OAuth2 tokens and secure storage
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecrets
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
              # KMS permissions for decrypting secrets
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:GenerateDataKey
                Resource:
                  - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
              # Bedrock model permissions for AI operations (all regions)
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:GetFoundationModel
                  - bedrock:ListFoundationModels
                  - bedrock:GetInferenceProfile
                  - bedrock:ListInferenceProfiles
                Resource:
                  - 'arn:aws:bedrock:*::foundation-model/*'
                  - !Sub 'arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/*'
              # Bedrock model catalog
              - Effect: Allow
                Action:
                  - aws-marketplace:Subscribe
                  - aws-marketplace:Unsubscribe
                  - aws-marketplace:ViewSubscriptions
                Resource: '*'

  # Store execution role ARN in SSM for AgentCore CLI
  GatewayExecutionRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/incident/agentcore/gateway_iam_role
      Type: String
      Value: !GetAtt AgentCoreExecutionRole.Arn
      Description: IAM execution role ARN for AgentCore runtime
      Tags:
        Application: NetOps

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  WebClientId:
    Description: Web Application Client ID
    Value: !Ref WebUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-WebClientId"

  MachineClientId:
    Description: Machine Application Client ID
    Value: !Ref MachineUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-MachineClientId"

  CognitoDomain:
    Description: Cognito Domain
    Value: !Join
      - ''
      - - !Sub 'https://incident-analysis-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub "${AWS::StackName}-CognitoDomain"
